export interface TimeZoneI {
  'Internal ID': number | string;
  Name: string;
  'State/Prov': string;
  'Time Zone': string;
  Code: number | string;
}

export const getTimeZone = (internalId: number): TimeZoneI => {
  const timeZone = TimezoneEEUU.find(
    (item) => item['Internal ID'] === internalId,
  );
  return timeZone;
};

export const TimezoneEEUU: TimeZoneI[] = [
  {
    'Internal ID': 416,
    Name: '864 South Carolina EST',
    'State/Prov': 'Est',
    'Time Zone': '',
    Code: '864',
  },
  {
    'Internal ID': 1,
    Name: '201 New Jersey EST',
    'State/Prov': 'New Jersey',
    'Time Zone': 'EST',
    Code: '201',
  },
  {
    'Internal ID': 2,
    Name: '202 District of Columbia EST',
    'State/Prov': 'District of Columbia',
    'Time Zone': 'EST',
    Code: '202',
  },
  {
    'Internal ID': 3,
    Name: '203 Connecticut EST',
    'State/Prov': 'Connecticut',
    'Time Zone': 'EST',
    Code: '203',
  },
  {
    'Internal ID': 4,
    Name: '205 Alabama CST',
    'State/Prov': 'Alabama',
    'Time Zone': 'CST',
    Code: '205',
  },
  {
    'Internal ID': 5,
    Name: '206 Washington PST',
    'State/Prov': 'Washington',
    'Time Zone': 'PST',
    Code: '206',
  },
  {
    'Internal ID': 6,
    Name: '207 Maine EST',
    'State/Prov': 'Maine',
    'Time Zone': 'EST',
    Code: '207',
  },
  {
    'Internal ID': 7,
    Name: '208 Idaho MST',
    'State/Prov': 'Idaho',
    'Time Zone': 'MST',
    Code: '208',
  },
  {
    'Internal ID': 8,
    Name: '209 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '209',
  },
  {
    'Internal ID': 9,
    Name: '210 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '210',
  },
  {
    'Internal ID': 10,
    Name: '212 New York EST',
    'State/Prov': 'New York',
    'Time Zone': 'EST',
    Code: '212',
  },
  {
    'Internal ID': 11,
    Name: '213 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '213',
  },
  {
    'Internal ID': 12,
    Name: '214 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '214',
  },
  {
    'Internal ID': 13,
    Name: '215 Pennsylvania EST',
    'State/Prov': 'Pennsylvania',
    'Time Zone': 'EST',
    Code: '215',
  },
  {
    'Internal ID': 14,
    Name: '216 Ohio EST',
    'State/Prov': 'Ohio',
    'Time Zone': 'EST',
    Code: '216',
  },
  {
    'Internal ID': 15,
    Name: '217 Illinois CST',
    'State/Prov': 'Illinois',
    'Time Zone': 'CST',
    Code: '217',
  },
  {
    'Internal ID': 16,
    Name: '218 Minnesota CST',
    'State/Prov': 'Minnesota',
    'Time Zone': 'CST',
    Code: '218',
  },
  {
    'Internal ID': 17,
    Name: '219 Indiana CST',
    'State/Prov': 'Indiana',
    'Time Zone': 'CST',
    Code: '219',
  },
  {
    'Internal ID': 18,
    Name: '220 Ohio EST',
    'State/Prov': 'Ohio',
    'Time Zone': 'EST',
    Code: '220',
  },
  {
    'Internal ID': 19,
    Name: '224 Illinois CST',
    'State/Prov': 'Illinois',
    'Time Zone': 'CST',
    Code: '224',
  },
  {
    'Internal ID': 20,
    Name: '225 Louisiana CST',
    'State/Prov': 'Louisiana',
    'Time Zone': 'CST',
    Code: '225',
  },
  {
    'Internal ID': 21,
    Name: '228 Mississippi CST',
    'State/Prov': 'Mississippi',
    'Time Zone': 'CST',
    Code: '228',
  },
  {
    'Internal ID': 22,
    Name: '229 Georgia EST',
    'State/Prov': 'Georgia',
    'Time Zone': 'EST',
    Code: '229',
  },
  {
    'Internal ID': 23,
    Name: '231 Michigan EST',
    'State/Prov': 'Michigan',
    'Time Zone': 'EST',
    Code: '231',
  },
  {
    'Internal ID': 24,
    Name: '234 Ohio EST',
    'State/Prov': 'Ohio',
    'Time Zone': 'EST',
    Code: '234',
  },
  {
    'Internal ID': 25,
    Name: '239 Florida EST',
    'State/Prov': 'Florida',
    'Time Zone': 'EST',
    Code: '239',
  },
  {
    'Internal ID': 26,
    Name: '240 Maryland EST',
    'State/Prov': 'Maryland',
    'Time Zone': 'EST',
    Code: '240',
  },
  {
    'Internal ID': 27,
    Name: '248 Michigan EST',
    'State/Prov': 'Michigan',
    'Time Zone': 'EST',
    Code: '248',
  },
  {
    'Internal ID': 28,
    Name: '251 Alabama CST',
    'State/Prov': 'Alabama',
    'Time Zone': 'CST',
    Code: '251',
  },
  {
    'Internal ID': 29,
    Name: '252 North Carolina EST',
    'State/Prov': 'North Carolina',
    'Time Zone': 'EST',
    Code: '252',
  },
  {
    'Internal ID': 30,
    Name: '253 Washington PST',
    'State/Prov': 'Washington',
    'Time Zone': 'PST',
    Code: '253',
  },
  {
    'Internal ID': 31,
    Name: '254 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '254',
  },
  {
    'Internal ID': 32,
    Name: '256 Alabama CST',
    'State/Prov': 'Alabama',
    'Time Zone': 'CST',
    Code: '256',
  },
  {
    'Internal ID': 33,
    Name: '260 Indiana EST',
    'State/Prov': 'Indiana',
    'Time Zone': 'EST',
    Code: '260',
  },
  {
    'Internal ID': 34,
    Name: '262 Wisconsin CST',
    'State/Prov': 'Wisconsin',
    'Time Zone': 'CST',
    Code: '262',
  },
  {
    'Internal ID': 35,
    Name: '267 Pennsylvania EST',
    'State/Prov': 'Pennsylvania',
    'Time Zone': 'EST',
    Code: '267',
  },
  {
    'Internal ID': 36,
    Name: '269 Michigan EST',
    'State/Prov': 'Michigan',
    'Time Zone': 'EST',
    Code: '269',
  },
  {
    'Internal ID': 37,
    Name: '270 Kentucky CST',
    'State/Prov': 'Kentucky',
    'Time Zone': 'CST',
    Code: '270',
  },
  {
    'Internal ID': 38,
    Name: '272 Pennsylvania EST',
    'State/Prov': 'Pennsylvania',
    'Time Zone': 'EST',
    Code: '272',
  },
  {
    'Internal ID': 39,
    Name: '276 Virginia EST',
    'State/Prov': 'Virginia',
    'Time Zone': 'EST',
    Code: '276',
  },
  {
    'Internal ID': 40,
    Name: '281 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '281',
  },
  {
    'Internal ID': 41,
    Name: '301 Maryland EST',
    'State/Prov': 'Maryland',
    'Time Zone': 'EST',
    Code: '301',
  },
  {
    'Internal ID': 42,
    Name: '302 Delaware EST',
    'State/Prov': 'Delaware',
    'Time Zone': 'EST',
    Code: '302',
  },
  {
    'Internal ID': 43,
    Name: '303 Colorado MST',
    'State/Prov': 'Colorado',
    'Time Zone': 'MST',
    Code: '303',
  },
  {
    'Internal ID': 44,
    Name: '304 West Virginia EST',
    'State/Prov': 'West Virginia',
    'Time Zone': 'EST',
    Code: '304',
  },
  {
    'Internal ID': 427,
    Name: '305 Florida EST',
    'State/Prov': 'Florida',
    'Time Zone': 'EST',
    Code: '305',
  },
  {
    'Internal ID': 46,
    Name: '307 Wyoming MST',
    'State/Prov': 'Wyoming',
    'Time Zone': 'MST',
    Code: '307',
  },
  {
    'Internal ID': 47,
    Name: '308 Nebraska CST',
    'State/Prov': 'Nebraska',
    'Time Zone': 'CST',
    Code: '308',
  },
  {
    'Internal ID': 48,
    Name: '309 Illinois CST',
    'State/Prov': 'Illinois',
    'Time Zone': 'CST',
    Code: '309',
  },
  {
    'Internal ID': 49,
    Name: '310 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '310',
  },
  {
    'Internal ID': 50,
    Name: '312 Illinois CST',
    'State/Prov': 'Illinois',
    'Time Zone': 'CST',
    Code: '312',
  },
  {
    'Internal ID': 51,
    Name: '313 Michigan EST',
    'State/Prov': 'Michigan',
    'Time Zone': 'EST',
    Code: '313',
  },
  {
    'Internal ID': 52,
    Name: '314 Missouri CST',
    'State/Prov': 'Missouri',
    'Time Zone': 'CST',
    Code: '314',
  },
  {
    'Internal ID': 53,
    Name: '315 New York EST',
    'State/Prov': 'New York',
    'Time Zone': 'EST',
    Code: '315',
  },
  {
    'Internal ID': 54,
    Name: '316 Kansas CST',
    'State/Prov': 'Kansas',
    'Time Zone': 'CST',
    Code: '316',
  },
  {
    'Internal ID': 55,
    Name: '317 Indiana EST',
    'State/Prov': 'Indiana',
    'Time Zone': 'EST',
    Code: '317',
  },
  {
    'Internal ID': 56,
    Name: '318 Louisiana CST',
    'State/Prov': 'Louisiana',
    'Time Zone': 'CST',
    Code: '318',
  },
  {
    'Internal ID': 57,
    Name: '319 Iowa CST',
    'State/Prov': 'Iowa',
    'Time Zone': 'CST',
    Code: '319',
  },
  {
    'Internal ID': 58,
    Name: '320 Minnesota CST',
    'State/Prov': 'Minnesota',
    'Time Zone': 'CST',
    Code: '320',
  },
  {
    'Internal ID': 59,
    Name: '321 Florida EST',
    'State/Prov': 'Florida',
    'Time Zone': 'EST',
    Code: '321',
  },
  {
    'Internal ID': 60,
    Name: '323 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '323',
  },
  {
    'Internal ID': 61,
    Name: '325 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '325',
  },
  {
    'Internal ID': 62,
    Name: '330 Ohio EST',
    'State/Prov': 'Ohio',
    'Time Zone': 'EST',
    Code: '330',
  },
  {
    'Internal ID': 63,
    Name: '331 Illinois CST',
    'State/Prov': 'Illinois',
    'Time Zone': 'CST',
    Code: '331',
  },
  {
    'Internal ID': 64,
    Name: '334 Alabama CST',
    'State/Prov': 'Alabama',
    'Time Zone': 'CST',
    Code: '334',
  },
  {
    'Internal ID': 65,
    Name: '336 North Carolina EST',
    'State/Prov': 'North Carolina',
    'Time Zone': 'EST',
    Code: '336',
  },
  {
    'Internal ID': 66,
    Name: '337 Louisiana CST',
    'State/Prov': 'Louisiana',
    'Time Zone': 'CST',
    Code: '337',
  },
  {
    'Internal ID': 67,
    Name: '339 Massachusetts EST',
    'State/Prov': 'Massachusetts',
    'Time Zone': 'EST',
    Code: '339',
  },
  {
    'Internal ID': 68,
    Name: '346 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '346',
  },
  {
    'Internal ID': 69,
    Name: '347 New York EST',
    'State/Prov': 'New York',
    'Time Zone': 'EST',
    Code: '347',
  },
  {
    'Internal ID': 70,
    Name: '351 Massachusetts EST',
    'State/Prov': 'Massachusetts',
    'Time Zone': 'EST',
    Code: '351',
  },
  {
    'Internal ID': 71,
    Name: '352 Florida EST',
    'State/Prov': 'Florida',
    'Time Zone': 'EST',
    Code: '352',
  },
  {
    'Internal ID': 72,
    Name: '360 Washington PST',
    'State/Prov': 'Washington',
    'Time Zone': 'PST',
    Code: '360',
  },
  {
    'Internal ID': 73,
    Name: '361 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '361',
  },
  {
    'Internal ID': 74,
    Name: '364 Kentucky CST',
    'State/Prov': 'Kentucky',
    'Time Zone': 'CST',
    Code: '364',
  },
  {
    'Internal ID': 75,
    Name: '380 Ohio EST',
    'State/Prov': 'Ohio',
    'Time Zone': 'EST',
    Code: '380',
  },
  {
    'Internal ID': 76,
    Name: '385 Utah MST',
    'State/Prov': 'Utah',
    'Time Zone': 'MST',
    Code: '385',
  },
  {
    'Internal ID': 77,
    Name: '386 Florida EST',
    'State/Prov': 'Florida',
    'Time Zone': 'EST',
    Code: '386',
  },
  {
    'Internal ID': 78,
    Name: '401 Rhode Island EST',
    'State/Prov': 'Rhode Island',
    'Time Zone': 'EST',
    Code: '401',
  },
  {
    'Internal ID': 79,
    Name: '402 Nebraska CST',
    'State/Prov': 'Nebraska',
    'Time Zone': 'CST',
    Code: '402',
  },
  {
    'Internal ID': 80,
    Name: '404 Georgia EST',
    'State/Prov': 'Georgia',
    'Time Zone': 'EST',
    Code: '404',
  },
  {
    'Internal ID': 81,
    Name: '405 Oklahoma CST',
    'State/Prov': 'Oklahoma',
    'Time Zone': 'CST',
    Code: '405',
  },
  {
    'Internal ID': 82,
    Name: '406 Montana MST',
    'State/Prov': 'Montana',
    'Time Zone': 'MST',
    Code: '406',
  },
  {
    'Internal ID': 83,
    Name: '407 Florida EST',
    'State/Prov': 'Florida',
    'Time Zone': 'EST',
    Code: '407',
  },
  {
    'Internal ID': 84,
    Name: '408 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '408',
  },
  {
    'Internal ID': 85,
    Name: '409 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '409',
  },
  {
    'Internal ID': 86,
    Name: '410 Maryland EST',
    'State/Prov': 'Maryland',
    'Time Zone': 'EST',
    Code: '410',
  },
  {
    'Internal ID': 87,
    Name: '412 Pennsylvania EST',
    'State/Prov': 'Pennsylvania',
    'Time Zone': 'EST',
    Code: '412',
  },
  {
    'Internal ID': 88,
    Name: '413 Massachusetts EST',
    'State/Prov': 'Massachusetts',
    'Time Zone': 'EST',
    Code: '413',
  },
  {
    'Internal ID': 89,
    Name: '414 Wisconsin CST',
    'State/Prov': 'Wisconsin',
    'Time Zone': 'CST',
    Code: '414',
  },
  {
    'Internal ID': 90,
    Name: '415 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '415',
  },
  {
    'Internal ID': 91,
    Name: '417 Missouri CST',
    'State/Prov': 'Missouri',
    'Time Zone': 'CST',
    Code: '417',
  },
  {
    'Internal ID': 92,
    Name: '419 Ohio EST',
    'State/Prov': 'Ohio',
    'Time Zone': 'EST',
    Code: '419',
  },
  {
    'Internal ID': 93,
    Name: '423 Tennessee EST',
    'State/Prov': 'Tennessee',
    'Time Zone': 'EST',
    Code: '423',
  },
  {
    'Internal ID': 94,
    Name: '424 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '424',
  },
  {
    'Internal ID': 95,
    Name: '425 Washington PST',
    'State/Prov': 'Washington',
    'Time Zone': 'PST',
    Code: '425',
  },
  {
    'Internal ID': 96,
    Name: '430 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '430',
  },
  {
    'Internal ID': 97,
    Name: '432 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '432',
  },
  {
    'Internal ID': 98,
    Name: '434 Virginia EST',
    'State/Prov': 'Virginia',
    'Time Zone': 'EST',
    Code: '434',
  },
  {
    'Internal ID': 99,
    Name: '435 Utah MST',
    'State/Prov': 'Utah',
    'Time Zone': 'MST',
    Code: '435',
  },
  {
    'Internal ID': 100,
    Name: '440 Ohio EST',
    'State/Prov': 'Ohio',
    'Time Zone': 'EST',
    Code: '440',
  },
  {
    'Internal ID': 101,
    Name: '442 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '442',
  },
  {
    'Internal ID': 102,
    Name: '443 Maryland EST',
    'State/Prov': 'Maryland',
    'Time Zone': 'EST',
    Code: '443',
  },
  {
    'Internal ID': 103,
    Name: '458 Oregon PST',
    'State/Prov': 'Oregon',
    'Time Zone': 'PST',
    Code: '458',
  },
  {
    'Internal ID': 104,
    Name: '469 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '469',
  },
  {
    'Internal ID': 105,
    Name: '470 Georgia EST',
    'State/Prov': 'Georgia',
    'Time Zone': 'EST',
    Code: '470',
  },
  {
    'Internal ID': 106,
    Name: '475 Connecticut EST',
    'State/Prov': 'Connecticut',
    'Time Zone': 'EST',
    Code: '475',
  },
  {
    'Internal ID': 107,
    Name: '478 Georgia EST',
    'State/Prov': 'Georgia',
    'Time Zone': 'EST',
    Code: '478',
  },
  {
    'Internal ID': 108,
    Name: '479 Arkansas CST',
    'State/Prov': 'Arkansas',
    'Time Zone': 'CST',
    Code: '479',
  },
  {
    'Internal ID': 109,
    Name: '480 Arizona MST',
    'State/Prov': 'Arizona',
    'Time Zone': 'MST',
    Code: '480',
  },
  {
    'Internal ID': 110,
    Name: '484 Pennsylvania EST',
    'State/Prov': 'Pennsylvania',
    'Time Zone': 'EST',
    Code: '484',
  },
  {
    'Internal ID': 111,
    Name: '501 Arkansas CST',
    'State/Prov': 'Arkansas',
    'Time Zone': 'CST',
    Code: '501',
  },
  {
    'Internal ID': 112,
    Name: '502 Kentucky EST',
    'State/Prov': 'Kentucky',
    'Time Zone': 'EST',
    Code: '502',
  },
  {
    'Internal ID': 113,
    Name: '503 Oregon PST',
    'State/Prov': 'Oregon',
    'Time Zone': 'PST',
    Code: '503',
  },
  {
    'Internal ID': 114,
    Name: '504 Louisiana CST',
    'State/Prov': 'Louisiana',
    'Time Zone': 'CST',
    Code: '504',
  },
  {
    'Internal ID': 115,
    Name: '505 New Mexico MST',
    'State/Prov': 'New Mexico',
    'Time Zone': 'MST',
    Code: '505',
  },
  {
    'Internal ID': 116,
    Name: '507 Minnesota CST',
    'State/Prov': 'Minnesota',
    'Time Zone': 'CST',
    Code: '507',
  },
  {
    'Internal ID': 117,
    Name: '508 Massachusetts EST',
    'State/Prov': 'Massachusetts',
    'Time Zone': 'EST',
    Code: '508',
  },
  {
    'Internal ID': 118,
    Name: '509 Washington PST',
    'State/Prov': 'Washington',
    'Time Zone': 'PST',
    Code: '509',
  },
  {
    'Internal ID': 119,
    Name: '510 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '510',
  },
  {
    'Internal ID': 120,
    Name: '512 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '512',
  },
  {
    'Internal ID': 121,
    Name: '513 Ohio EST',
    'State/Prov': 'Ohio',
    'Time Zone': 'EST',
    Code: '513',
  },
  {
    'Internal ID': 122,
    Name: '515 Iowa CST',
    'State/Prov': 'Iowa',
    'Time Zone': 'CST',
    Code: '515',
  },
  {
    'Internal ID': 123,
    Name: '516 New York EST',
    'State/Prov': 'New York',
    'Time Zone': 'EST',
    Code: '516',
  },
  {
    'Internal ID': 124,
    Name: '517 Michigan EST',
    'State/Prov': 'Michigan',
    'Time Zone': 'EST',
    Code: '517',
  },
  {
    'Internal ID': 125,
    Name: '518 New York EST',
    'State/Prov': 'New York',
    'Time Zone': 'EST',
    Code: '518',
  },
  {
    'Internal ID': 126,
    Name: '520 Arizona MST',
    'State/Prov': 'Arizona',
    'Time Zone': 'MST',
    Code: '520',
  },
  {
    'Internal ID': 127,
    Name: '530 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '530',
  },
  {
    'Internal ID': 128,
    Name: '531 Nebraska CST',
    'State/Prov': 'Nebraska',
    'Time Zone': 'CST',
    Code: '531',
  },
  {
    'Internal ID': 129,
    Name: '534 Wisconsin CST',
    'State/Prov': 'Wisconsin',
    'Time Zone': 'CST',
    Code: '534',
  },
  {
    'Internal ID': 130,
    Name: '539 Oklahoma CST',
    'State/Prov': 'Oklahoma',
    'Time Zone': 'CST',
    Code: '539',
  },
  {
    'Internal ID': 131,
    Name: '540 Virginia EST',
    'State/Prov': 'Virginia',
    'Time Zone': 'EST',
    Code: '540',
  },
  {
    'Internal ID': 132,
    Name: '541 Oregon PST',
    'State/Prov': 'Oregon',
    'Time Zone': 'PST',
    Code: '541',
  },
  {
    'Internal ID': 133,
    Name: '551 New Jersey EST',
    'State/Prov': 'New Jersey',
    'Time Zone': 'EST',
    Code: '551',
  },
  {
    'Internal ID': 134,
    Name: '559 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '559',
  },
  {
    'Internal ID': 135,
    Name: '561 Florida EST',
    'State/Prov': 'Florida',
    'Time Zone': 'EST',
    Code: '561',
  },
  {
    'Internal ID': 136,
    Name: '562 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '562',
  },
  {
    'Internal ID': 137,
    Name: '563 Iowa CST',
    'State/Prov': 'Iowa',
    'Time Zone': 'CST',
    Code: '563',
  },
  {
    'Internal ID': 138,
    Name: '567 Ohio EST',
    'State/Prov': 'Ohio',
    'Time Zone': 'EST',
    Code: '567',
  },
  {
    'Internal ID': 139,
    Name: '570 Pennsylvania EST',
    'State/Prov': 'Pennsylvania',
    'Time Zone': 'EST',
    Code: '570',
  },
  {
    'Internal ID': 140,
    Name: '571 Virginia EST',
    'State/Prov': 'Virginia',
    'Time Zone': 'EST',
    Code: '571',
  },
  {
    'Internal ID': 141,
    Name: '573 Missouri CST',
    'State/Prov': 'Missouri',
    'Time Zone': 'CST',
    Code: '573',
  },
  {
    'Internal ID': 142,
    Name: '574 Indiana EST',
    'State/Prov': 'Indiana',
    'Time Zone': 'EST',
    Code: '574',
  },
  {
    'Internal ID': 143,
    Name: '575 New Mexico MST',
    'State/Prov': 'New Mexico',
    'Time Zone': 'MST',
    Code: '575',
  },
  {
    'Internal ID': 144,
    Name: '580 Oklahoma CST',
    'State/Prov': 'Oklahoma',
    'Time Zone': 'CST',
    Code: '580',
  },
  {
    'Internal ID': 145,
    Name: '585 New York EST',
    'State/Prov': 'New York',
    'Time Zone': 'EST',
    Code: '585',
  },
  {
    'Internal ID': 146,
    Name: '586 Michigan EST',
    'State/Prov': 'Michigan',
    'Time Zone': 'EST',
    Code: '586',
  },
  {
    'Internal ID': 147,
    Name: '601 Mississippi CST',
    'State/Prov': 'Mississippi',
    'Time Zone': 'CST',
    Code: '601',
  },
  {
    'Internal ID': 148,
    Name: '602 Arizona MST',
    'State/Prov': 'Arizona',
    'Time Zone': 'MST',
    Code: '602',
  },
  {
    'Internal ID': 149,
    Name: '603 New Hampshire EST',
    'State/Prov': 'New Hampshire',
    'Time Zone': 'EST',
    Code: '603',
  },
  {
    'Internal ID': 150,
    Name: '605 South Dakota CST',
    'State/Prov': 'South Dakota',
    'Time Zone': 'CST',
    Code: '605',
  },
  {
    'Internal ID': 151,
    Name: '606 Kentucky EST',
    'State/Prov': 'Kentucky',
    'Time Zone': 'EST',
    Code: '606',
  },
  {
    'Internal ID': 152,
    Name: '607 New York EST',
    'State/Prov': 'New York',
    'Time Zone': 'EST',
    Code: '607',
  },
  {
    'Internal ID': 153,
    Name: '608 Wisconsin CST',
    'State/Prov': 'Wisconsin',
    'Time Zone': 'CST',
    Code: '608',
  },
  {
    'Internal ID': 154,
    Name: '609 New Jersey EST',
    'State/Prov': 'New Jersey',
    'Time Zone': 'EST',
    Code: '609',
  },
  {
    'Internal ID': 155,
    Name: '610 Pennsylvania EST',
    'State/Prov': 'Pennsylvania',
    'Time Zone': 'EST',
    Code: '610',
  },
  {
    'Internal ID': 156,
    Name: '612 Minnesota CST',
    'State/Prov': 'Minnesota',
    'Time Zone': 'CST',
    Code: '612',
  },
  {
    'Internal ID': 157,
    Name: '614 Ohio EST',
    'State/Prov': 'Ohio',
    'Time Zone': 'EST',
    Code: '614',
  },
  {
    'Internal ID': 158,
    Name: '615 Tennessee CST',
    'State/Prov': 'Tennessee',
    'Time Zone': 'CST',
    Code: '615',
  },
  {
    'Internal ID': 159,
    Name: '616 Michigan EST',
    'State/Prov': 'Michigan',
    'Time Zone': 'EST',
    Code: '616',
  },
  {
    'Internal ID': 160,
    Name: '617 Massachusetts EST',
    'State/Prov': 'Massachusetts',
    'Time Zone': 'EST',
    Code: '617',
  },
  {
    'Internal ID': 161,
    Name: '618 Illinois CST',
    'State/Prov': 'Illinois',
    'Time Zone': 'CST',
    Code: '618',
  },
  {
    'Internal ID': 162,
    Name: '619 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '619',
  },
  {
    'Internal ID': 163,
    Name: '620 Kansas CST',
    'State/Prov': 'Kansas',
    'Time Zone': 'CST',
    Code: '620',
  },
  {
    'Internal ID': 164,
    Name: '623 Arizona MST',
    'State/Prov': 'Arizona',
    'Time Zone': 'MST',
    Code: '623',
  },
  {
    'Internal ID': 165,
    Name: '626 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '626',
  },
  {
    'Internal ID': 166,
    Name: '628 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '628',
  },
  {
    'Internal ID': 167,
    Name: '629 Tennessee CST',
    'State/Prov': 'Tennessee',
    'Time Zone': 'CST',
    Code: '629',
  },
  {
    'Internal ID': 168,
    Name: '630 Illinois CST',
    'State/Prov': 'Illinois',
    'Time Zone': 'CST',
    Code: '630',
  },
  {
    'Internal ID': 169,
    Name: '631 New York EST',
    'State/Prov': 'New York',
    'Time Zone': 'EST',
    Code: '631',
  },
  {
    'Internal ID': 170,
    Name: '636 Missouri CST',
    'State/Prov': 'Missouri',
    'Time Zone': 'CST',
    Code: '636',
  },
  {
    'Internal ID': 171,
    Name: '641 Iowa CST',
    'State/Prov': 'Iowa',
    'Time Zone': 'CST',
    Code: '641',
  },
  {
    'Internal ID': 172,
    Name: '646 New York EST',
    'State/Prov': 'New York',
    'Time Zone': 'EST',
    Code: '646',
  },
  {
    'Internal ID': 173,
    Name: '650 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '650',
  },
  {
    'Internal ID': 174,
    Name: '651 Minnesota CST',
    'State/Prov': 'Minnesota',
    'Time Zone': 'CST',
    Code: '651',
  },
  {
    'Internal ID': 175,
    Name: '657 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '657',
  },
  {
    'Internal ID': 176,
    Name: '660 Missouri CST',
    'State/Prov': 'Missouri',
    'Time Zone': 'CST',
    Code: '660',
  },
  {
    'Internal ID': 177,
    Name: '661 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '661',
  },
  {
    'Internal ID': 178,
    Name: '662 Mississippi CST',
    'State/Prov': 'Mississippi',
    'Time Zone': 'CST',
    Code: '662',
  },
  {
    'Internal ID': 179,
    Name: '667 Maryland EST',
    'State/Prov': 'Maryland',
    'Time Zone': 'EST',
    Code: '667',
  },
  {
    'Internal ID': 180,
    Name: '669 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '669',
  },
  {
    'Internal ID': 181,
    Name: '678 Georgia EST',
    'State/Prov': 'Georgia',
    'Time Zone': 'EST',
    Code: '678',
  },
  {
    'Internal ID': 182,
    Name: '681 West Virginia EST',
    'State/Prov': 'West Virginia',
    'Time Zone': 'EST',
    Code: '681',
  },
  {
    'Internal ID': 183,
    Name: '682 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '682',
  },
  {
    'Internal ID': 184,
    Name: '701 North Dakota CST',
    'State/Prov': 'North Dakota',
    'Time Zone': 'CST',
    Code: '701',
  },
  {
    'Internal ID': 45,
    Name: '702 Nevada PST',
    'State/Prov': 'Florida',
    'Time Zone': 'PST',
    Code: '702',
  },
  {
    'Internal ID': 185,
    Name: '702 Nevada PST',
    'State/Prov': 'Nevada',
    'Time Zone': 'PST',
    Code: '702',
  },
  {
    'Internal ID': 186,
    Name: '703 Virginia EST',
    'State/Prov': 'Virginia',
    'Time Zone': 'EST',
    Code: '703',
  },
  {
    'Internal ID': 187,
    Name: '704 North Carolina EST',
    'State/Prov': 'North Carolina',
    'Time Zone': 'EST',
    Code: '704',
  },
  {
    'Internal ID': 188,
    Name: '706 Georgia EST',
    'State/Prov': 'Georgia',
    'Time Zone': 'EST',
    Code: '706',
  },
  {
    'Internal ID': 189,
    Name: '707 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '707',
  },
  {
    'Internal ID': 190,
    Name: '708 Illinois CST',
    'State/Prov': 'Illinois',
    'Time Zone': 'CST',
    Code: '708',
  },
  {
    'Internal ID': 191,
    Name: '712 Iowa CST',
    'State/Prov': 'Iowa',
    'Time Zone': 'CST',
    Code: '712',
  },
  {
    'Internal ID': 192,
    Name: '713 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '713',
  },
  {
    'Internal ID': 193,
    Name: '714 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '714',
  },
  {
    'Internal ID': 194,
    Name: '715 Wisconsin CST',
    'State/Prov': 'Wisconsin',
    'Time Zone': 'CST',
    Code: '715',
  },
  {
    'Internal ID': 195,
    Name: '716 New York EST',
    'State/Prov': 'New York',
    'Time Zone': 'EST',
    Code: '716',
  },
  {
    'Internal ID': 196,
    Name: '717 Pennsylvania EST',
    'State/Prov': 'Pennsylvania',
    'Time Zone': 'EST',
    Code: '717',
  },
  {
    'Internal ID': 197,
    Name: '718 New York EST',
    'State/Prov': 'New York',
    'Time Zone': 'EST',
    Code: '718',
  },
  {
    'Internal ID': 198,
    Name: '719 Colorado MST',
    'State/Prov': 'Colorado',
    'Time Zone': 'MST',
    Code: '719',
  },
  {
    'Internal ID': 199,
    Name: '720 Colorado MST',
    'State/Prov': 'Colorado',
    'Time Zone': 'MST',
    Code: '720',
  },
  {
    'Internal ID': 200,
    Name: '724 Pennsylvania EST',
    'State/Prov': 'Pennsylvania',
    'Time Zone': 'EST',
    Code: '724',
  },
  {
    'Internal ID': 201,
    Name: '725 Nevada PST',
    'State/Prov': 'Nevada',
    'Time Zone': 'PST',
    Code: '725',
  },
  {
    'Internal ID': 202,
    Name: '727 Florida EST',
    'State/Prov': 'Florida',
    'Time Zone': 'EST',
    Code: '727',
  },
  {
    'Internal ID': 203,
    Name: '731 Tennessee CST',
    'State/Prov': 'Tennessee',
    'Time Zone': 'CST',
    Code: '731',
  },
  {
    'Internal ID': 204,
    Name: '732 New Jersey EST',
    'State/Prov': 'New Jersey',
    'Time Zone': 'EST',
    Code: '732',
  },
  {
    'Internal ID': 205,
    Name: '734 Michigan EST',
    'State/Prov': 'Michigan',
    'Time Zone': 'EST',
    Code: '734',
  },
  {
    'Internal ID': 206,
    Name: '737 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '737',
  },
  {
    'Internal ID': 207,
    Name: '740 Ohio EST',
    'State/Prov': 'Ohio',
    'Time Zone': 'EST',
    Code: '740',
  },
  {
    'Internal ID': 208,
    Name: '743 North Carolina EST',
    'State/Prov': 'North Carolina',
    'Time Zone': 'EST',
    Code: '743',
  },
  {
    'Internal ID': 209,
    Name: '747 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '747',
  },
  {
    'Internal ID': 210,
    Name: '754 Florida EST',
    'State/Prov': 'Florida',
    'Time Zone': 'EST',
    Code: '754',
  },
  {
    'Internal ID': 211,
    Name: '757 Virginia EST',
    'State/Prov': 'Virginia',
    'Time Zone': 'EST',
    Code: '757',
  },
  {
    'Internal ID': 212,
    Name: '760 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '760',
  },
  {
    'Internal ID': 213,
    Name: '762 Georgia EST',
    'State/Prov': 'Georgia',
    'Time Zone': 'EST',
    Code: '762',
  },
  {
    'Internal ID': 214,
    Name: '763 Minnesota CST',
    'State/Prov': 'Minnesota',
    'Time Zone': 'CST',
    Code: '763',
  },
  {
    'Internal ID': 215,
    Name: '765 Indiana EST',
    'State/Prov': 'Indiana',
    'Time Zone': 'EST',
    Code: '765',
  },
  {
    'Internal ID': 216,
    Name: '769 Mississippi CST',
    'State/Prov': 'Mississippi',
    'Time Zone': 'CST',
    Code: '769',
  },
  {
    'Internal ID': 217,
    Name: '770 Georgia EST',
    'State/Prov': 'Georgia',
    'Time Zone': 'EST',
    Code: '770',
  },
  {
    'Internal ID': 218,
    Name: '772 Florida EST',
    'State/Prov': 'Florida',
    'Time Zone': 'EST',
    Code: '772',
  },
  {
    'Internal ID': 219,
    Name: '773 Illinois CST',
    'State/Prov': 'Illinois',
    'Time Zone': 'CST',
    Code: '773',
  },
  {
    'Internal ID': 220,
    Name: '774 Massachusetts EST',
    'State/Prov': 'Massachusetts',
    'Time Zone': 'EST',
    Code: '774',
  },
  {
    'Internal ID': 221,
    Name: '775 Nevada PST',
    'State/Prov': 'Nevada',
    'Time Zone': 'PST',
    Code: '775',
  },
  {
    'Internal ID': 222,
    Name: '779 Illinois CST',
    'State/Prov': 'Illinois',
    'Time Zone': 'CST',
    Code: '779',
  },
  {
    'Internal ID': 223,
    Name: '781 Massachusetts EST',
    'State/Prov': 'Massachusetts',
    'Time Zone': 'EST',
    Code: '781',
  },
  {
    'Internal ID': 224,
    Name: '785 Kansas CST',
    'State/Prov': 'Kansas',
    'Time Zone': 'CST',
    Code: '785',
  },
  {
    'Internal ID': 225,
    Name: '786 Florida EST',
    'State/Prov': 'Florida',
    'Time Zone': 'EST',
    Code: '786',
  },
  {
    'Internal ID': 401,
    Name: '787 Puerto Rico',
    'State/Prov': 'Puerto Rico',
    'Time Zone': 'AST',
    Code: '787',
  },
  {
    'Internal ID': 226,
    Name: '801 Utah MST',
    'State/Prov': 'Utah',
    'Time Zone': 'MST',
    Code: '801',
  },
  {
    'Internal ID': 227,
    Name: '802 Vermont EST',
    'State/Prov': 'Vermont',
    'Time Zone': 'EST',
    Code: '802',
  },
  {
    'Internal ID': 228,
    Name: '803 South Carolina EST',
    'State/Prov': 'South Carolina',
    'Time Zone': 'EST',
    Code: '803',
  },
  {
    'Internal ID': 229,
    Name: '804 Virginia EST',
    'State/Prov': 'Virginia',
    'Time Zone': 'EST',
    Code: '804',
  },
  {
    'Internal ID': 230,
    Name: '805 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '805',
  },
  {
    'Internal ID': 231,
    Name: '806 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '806',
  },
  {
    'Internal ID': 232,
    Name: '808 Hawaii HAST',
    'State/Prov': 'Hawaii',
    'Time Zone': 'HAST',
    Code: '808',
  },
  {
    'Internal ID': 233,
    Name: '809 República Dominicana AST',
    'State/Prov': 'República Dominicana',
    'Time Zone': 'AST',
    Code: '809',
  },
  {
    'Internal ID': 234,
    Name: '810 Michigan EST',
    'State/Prov': 'Michigan',
    'Time Zone': 'EST',
    Code: '810',
  },
  {
    'Internal ID': 235,
    Name: '812 Indiana EST',
    'State/Prov': 'Indiana',
    'Time Zone': 'EST',
    Code: '812',
  },
  {
    'Internal ID': 236,
    Name: '813 Florida EST',
    'State/Prov': 'Florida',
    'Time Zone': 'EST',
    Code: '813',
  },
  {
    'Internal ID': 237,
    Name: '814 Pennsylvania EST',
    'State/Prov': 'Pennsylvania',
    'Time Zone': 'EST',
    Code: '814',
  },
  {
    'Internal ID': 238,
    Name: '815 Illinois CST',
    'State/Prov': 'Illinois',
    'Time Zone': 'CST',
    Code: '815',
  },
  {
    'Internal ID': 239,
    Name: '816 Missouri CST',
    'State/Prov': 'Missouri',
    'Time Zone': 'CST',
    Code: '816',
  },
  {
    'Internal ID': 240,
    Name: '817 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '817',
  },
  {
    'Internal ID': 241,
    Name: '818 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '818',
  },
  {
    'Internal ID': 242,
    Name: '828 North Carolina EST',
    'State/Prov': 'North Carolina',
    'Time Zone': 'EST',
    Code: '828',
  },
  {
    'Internal ID': 243,
    Name: '830 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '830',
  },
  {
    'Internal ID': 244,
    Name: '831 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '831',
  },
  {
    'Internal ID': 245,
    Name: '832 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '832',
  },
  {
    'Internal ID': 246,
    Name: '843 South Carolina EST',
    'State/Prov': 'South Carolina',
    'Time Zone': 'EST',
    Code: '843',
  },
  {
    'Internal ID': 247,
    Name: '845 New York EST',
    'State/Prov': 'New York',
    'Time Zone': 'EST',
    Code: '845',
  },
  {
    'Internal ID': 248,
    Name: '847 Illinois CST',
    'State/Prov': 'Illinois',
    'Time Zone': 'CST',
    Code: '847',
  },
  {
    'Internal ID': 249,
    Name: '848 New Jersey EST',
    'State/Prov': 'New Jersey',
    'Time Zone': 'EST',
    Code: '848',
  },
  {
    'Internal ID': 250,
    Name: '850 Florida CST',
    'State/Prov': 'Florida',
    'Time Zone': 'CST',
    Code: '850',
  },
  {
    'Internal ID': 251,
    Name: '854 South Carolina EST',
    'State/Prov': 'South Carolina',
    'Time Zone': 'EST',
    Code: '854',
  },
  {
    'Internal ID': 252,
    Name: '856 New Jersey EST',
    'State/Prov': 'New Jersey',
    'Time Zone': 'EST',
    Code: '856',
  },
  {
    'Internal ID': 253,
    Name: '857 Massachusetts EST',
    'State/Prov': 'Massachusetts',
    'Time Zone': 'EST',
    Code: '857',
  },
  {
    'Internal ID': 254,
    Name: '858 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '858',
  },
  {
    'Internal ID': 255,
    Name: '859 Kentucky EST',
    'State/Prov': 'Kentucky',
    'Time Zone': 'EST',
    Code: '859',
  },
  {
    'Internal ID': 256,
    Name: '860 Connecticut EST',
    'State/Prov': 'Connecticut',
    'Time Zone': 'EST',
    Code: '860',
  },
  {
    'Internal ID': 257,
    Name: '862 New Jersey EST',
    'State/Prov': 'New Jersey',
    'Time Zone': 'EST',
    Code: '862',
  },
  {
    'Internal ID': 258,
    Name: '863 Florida EST',
    'State/Prov': 'Florida',
    'Time Zone': 'EST',
    Code: '863',
  },
  {
    'Internal ID': 259,
    Name: '864 South Carolina EST',
    'State/Prov': 'South Carolina',
    'Time Zone': 'EST',
    Code: '864',
  },
  {
    'Internal ID': 260,
    Name: '865 Tennessee EST',
    'State/Prov': 'Tennessee',
    'Time Zone': 'EST',
    Code: '865',
  },
  {
    'Internal ID': 261,
    Name: '870 Arkansas CST',
    'State/Prov': 'Arkansas',
    'Time Zone': 'CST',
    Code: '870',
  },
  {
    'Internal ID': 262,
    Name: '872 Illinois CST',
    'State/Prov': 'Illinois',
    'Time Zone': 'CST',
    Code: '872',
  },
  {
    'Internal ID': 263,
    Name: '878 Pennsylvania EST',
    'State/Prov': 'Pennsylvania',
    'Time Zone': 'EST',
    Code: '878',
  },
  {
    'Internal ID': 264,
    Name: '901 Tennessee CST',
    'State/Prov': 'Tennessee',
    'Time Zone': 'CST',
    Code: '901',
  },
  {
    'Internal ID': 265,
    Name: '903 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '903',
  },
  {
    'Internal ID': 266,
    Name: '904 Florida EST',
    'State/Prov': 'Florida',
    'Time Zone': 'EST',
    Code: '904',
  },
  {
    'Internal ID': 267,
    Name: '906 Michigan EST',
    'State/Prov': 'Michigan',
    'Time Zone': 'EST',
    Code: '906',
  },
  {
    'Internal ID': 268,
    Name: '907 Alaska AKST',
    'State/Prov': 'Alaska',
    'Time Zone': 'AKST',
    Code: '907',
  },
  {
    'Internal ID': 269,
    Name: '908 New Jersey EST',
    'State/Prov': 'New Jersey',
    'Time Zone': 'EST',
    Code: '908',
  },
  {
    'Internal ID': 270,
    Name: '909 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '909',
  },
  {
    'Internal ID': 271,
    Name: '910 North Carolina EST',
    'State/Prov': 'North Carolina',
    'Time Zone': 'EST',
    Code: '910',
  },
  {
    'Internal ID': 272,
    Name: '912 Georgia EST',
    'State/Prov': 'Georgia',
    'Time Zone': 'EST',
    Code: '912',
  },
  {
    'Internal ID': 273,
    Name: '913 Kansas CST',
    'State/Prov': 'Kansas',
    'Time Zone': 'CST',
    Code: '913',
  },
  {
    'Internal ID': 274,
    Name: '914 New York EST',
    'State/Prov': 'New York',
    'Time Zone': 'EST',
    Code: '914',
  },
  {
    'Internal ID': 275,
    Name: '915 Texas MST',
    'State/Prov': 'Texas',
    'Time Zone': 'MST',
    Code: '915',
  },
  {
    'Internal ID': 276,
    Name: '916 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '916',
  },
  {
    'Internal ID': 277,
    Name: '917 New York EST',
    'State/Prov': 'New York',
    'Time Zone': 'EST',
    Code: '917',
  },
  {
    'Internal ID': 278,
    Name: '918 Oklahoma CST',
    'State/Prov': 'Oklahoma',
    'Time Zone': 'CST',
    Code: '918',
  },
  {
    'Internal ID': 279,
    Name: '919 North Carolina EST',
    'State/Prov': 'North Carolina',
    'Time Zone': 'EST',
    Code: '919',
  },
  {
    'Internal ID': 280,
    Name: '920 Wisconsin CST',
    'State/Prov': 'Wisconsin',
    'Time Zone': 'CST',
    Code: '920',
  },
  {
    'Internal ID': 281,
    Name: '925 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '925',
  },
  {
    'Internal ID': 282,
    Name: '928 Arizona MST',
    'State/Prov': 'Arizona',
    'Time Zone': 'MST',
    Code: '928',
  },
  {
    'Internal ID': 283,
    Name: '929 New York EST',
    'State/Prov': 'New York',
    'Time Zone': 'EST',
    Code: '929',
  },
  {
    'Internal ID': 284,
    Name: '930 Indiana EST',
    'State/Prov': 'Indiana',
    'Time Zone': 'EST',
    Code: '930',
  },
  {
    'Internal ID': 285,
    Name: '931 Tennessee CST',
    'State/Prov': 'Tennessee',
    'Time Zone': 'CST',
    Code: '931',
  },
  {
    'Internal ID': 286,
    Name: '934 New York EST',
    'State/Prov': 'New York',
    'Time Zone': 'EST',
    Code: '934',
  },
  {
    'Internal ID': 287,
    Name: '936 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '936',
  },
  {
    'Internal ID': 288,
    Name: '937 Ohio EST',
    'State/Prov': 'Ohio',
    'Time Zone': 'EST',
    Code: '937',
  },
  {
    'Internal ID': 289,
    Name: '938 Alabama CST',
    'State/Prov': 'Alabama',
    'Time Zone': 'CST',
    Code: '938',
  },
  {
    'Internal ID': 402,
    Name: '939 Puerto Rico',
    'State/Prov': 'Puerto Rico',
    'Time Zone': 'AST',
    Code: '939',
  },
  {
    'Internal ID': 290,
    Name: '940 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '940',
  },
  {
    'Internal ID': 291,
    Name: '941 Florida EST',
    'State/Prov': 'Florida',
    'Time Zone': 'EST',
    Code: '941',
  },
  {
    'Internal ID': 407,
    Name: '941 Florida EST',
    'State/Prov': 'Las Vegas',
    'Time Zone': 'EST',
    Code: '941',
  },
  {
    'Internal ID': 292,
    Name: '947 Michigan EST',
    'State/Prov': 'Michigan',
    'Time Zone': 'EST',
    Code: '947',
  },
  {
    'Internal ID': 293,
    Name: '949 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '949',
  },
  {
    'Internal ID': 294,
    Name: '951 California PST',
    'State/Prov': 'California',
    'Time Zone': 'PST',
    Code: '951',
  },
  {
    'Internal ID': 295,
    Name: '952 Minnesota CST',
    'State/Prov': 'Minnesota',
    'Time Zone': 'CST',
    Code: '952',
  },
  {
    'Internal ID': 296,
    Name: '954 Florida EST',
    'State/Prov': 'Florida',
    'Time Zone': 'EST',
    Code: '954',
  },
  {
    'Internal ID': 297,
    Name: '956 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '956',
  },
  {
    'Internal ID': 298,
    Name: '959 Connecticut EST',
    'State/Prov': 'Connecticut',
    'Time Zone': 'EST',
    Code: '959',
  },
  {
    'Internal ID': 299,
    Name: '970 Colorado MST',
    'State/Prov': 'Colorado',
    'Time Zone': 'MST',
    Code: '970',
  },
  {
    'Internal ID': 300,
    Name: '971 Oregon PST',
    'State/Prov': 'Oregon',
    'Time Zone': 'PST',
    Code: '971',
  },
  {
    'Internal ID': 301,
    Name: '972 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '972',
  },
  {
    'Internal ID': 302,
    Name: '973 New Jersey EST',
    'State/Prov': 'New Jersey',
    'Time Zone': 'EST',
    Code: '973',
  },
  {
    'Internal ID': 303,
    Name: '978 Massachusetts EST',
    'State/Prov': 'Massachusetts',
    'Time Zone': 'EST',
    Code: '978',
  },
  {
    'Internal ID': 304,
    Name: '979 Texas CST',
    'State/Prov': 'Texas',
    'Time Zone': 'CST',
    Code: '979',
  },
  {
    'Internal ID': 305,
    Name: '980 North Carolina EST',
    'State/Prov': 'North Carolina',
    'Time Zone': 'EST',
    Code: '980',
  },
  {
    'Internal ID': 306,
    Name: '984 North Carolina EST',
    'State/Prov': 'North Carolina',
    'Time Zone': 'EST',
    Code: '984',
  },
  {
    'Internal ID': 307,
    Name: '985 Louisiana CST',
    'State/Prov': 'Louisiana',
    'Time Zone': 'CST',
    Code: '985',
  },
  {
    'Internal ID': 308,
    Name: '989 Michigan EST',
    'State/Prov': 'Michigan',
    'Time Zone': 'EST',
    Code: '989',
  },
  {
    'Internal ID': 414,
    Name: 'Colorado Springs',
    'State/Prov': '',
    'Time Zone': '',
    Code: '303',
  },
  {
    'Internal ID': 411,
    Name: 'Florida',
    'State/Prov': 'Florida/Oviedo',
    'Time Zone': 'EST',
    Code: '321',
  },
];
