export const tissiniPlusRelation = [
  {
    id: 1,
    name: 'Turquesa',
    premios: [
      'reconocimiento_turquesa',
      'beneficio_atencion_pref',
      'beneficio_dias_cambio_ad',
      'descue_primera_turquesa',
      'beneficio_conv_grant',
      'custentity_hrc_beneficio_market_place',
      'kit_basico_redes',
      'custentity_hrc_realiza3compras',
    ],
  },
  {
    id: 2,
    name: 'Celeste',
    premios: [
      'reconocimiento_celeste',
      'realiza3compras_celeste',
      'beneficio_primera_catalog',
      'descue_primera_celeste',
      'beneficio_tissini_academi',
      'kit_premium_redes',
    ],
  },
  {
    id: 3,
    name: 'Azul',
    premios: [
      'reconocimiento_azul',
      'beneficio_tissini_pref',
      'obsequio_tarjetas_tissini',
      'descue_primera_azul',
      'beneficio_regalo_cumple',
      'realiza3compras_azul',
    ],
  },
  {
    id: 3,
    name: 'Rosa',
    premios: [
      'dos_tiquets_aereos_intern',
      'reconocimiento_rosa',
      'descue_primera_rosa',
      'realiza3compras_rosa',
      'compra10_lleva11',
      'acumuladas_rosa',
      'kit_personalizado_boutiqu',
      'feria_emprendimiento',
      'publicidad_pagina_persona',
      'smarthphone_ult_gen',
      'look_entutalla',
      'reconocimiento_mejor',
      'compra10_lleva11_rosa',
    ],
  },
];
